name: SwiftShader

on:
  push:
    branches:
      - 'rc/**'
      - 'pr/action3' # TODO: remove this line
      - '**/trigger/swiftshader'

jobs:
  swiftshader:
    name: Test Filament + Vulkan + SwiftShader
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.0.0

    - name: Download Image with Pre-Built SwiftShader
      run: |
          docker pull ghcr.io/filament-assets/swiftshader:latest
          docker tag ghcr.io/filament-assets/swiftshader:latest ssfilament

    - name: Build Filament with SwiftShader Support
      run: |
          docker run -v `pwd`:/trees/branch ssfilament branch/build.sh -t release gltf_viewer
          mkdir results

    - name: Test Filament with SwiftShader
      continue-on-error: false # Temporarily set this to true to see the upload artifact on failure.
      timeout-minutes: 15
      run: >
          docker run
          --cap-add=SYS_PTRACE
          --security-opt seccomp=unconfined
          --security-opt apparmor=unconfined
          -t
          -v `pwd`:/trees/branch
          -w /trees/branch/results ssfilament
          /usr/bin/catchsegv
          /trees/branch/out/cmake-release/samples/gltf_viewer
          --headless
          --batch /trees/branch/libs/viewer/tests/basic.json
          -a vulkan

    # The results folder contains screenshots and settings files.
    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: results
        if-no-files-found: error
